### ISSUE TITLE
plugin.load is not a function

### ISSUE THREAD

**Issue by Akiyamka** [aurelia/app-contacts#43] opened 2017-05-27 11:54 UTC
**I'm submitting a bug report**

* **Library Version:**
0.27.0

**Environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v7.9.0

* **NPM Version:**
4.2.0

* **Webpack**
webpack 2.4.1

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
[On step 5](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/contact-manager-tutorial/5)
"When you run the application, you should see something like this:" but a see
`Uncaught TypeError: plugin.load is not a function`
`Unhandled rejection Error: Failed loading required CSS file: styles.css`

As I found out later, to fix this, I had to change the standard loader settings:
`"stub": true to false`.
So as a result it turned out:
```
    "loader": {
      "type": "require",
      "configTarget": "vendor-bundle.js",
      "includeBundleMetadataInConfig": "auto",
      "plugins": [
        {
          "name": "text",
          "extensions": [
            ".html",
            ".css"
          ],
          "stub": false
        }
      ]
    },
```
**Expected/desired behavior:**
This point should be mentioned in the lesson, or change the default settings of the loader
Especially since the problem has been known for a long time
https://github.com/aurelia/templating-resources/issues/220

**Comment by EisenbergEffect** [comment] 2017-05-31 03:39
@JeroenVinke Can you check this out to see if there's an issue with the CLI? This should work correctly with `stub: true` or with `stub: false`. Is it possible that the CSS isn't being bundled?

**Comment by JeroenVinke** [comment] 2017-05-31 07:13
This may be related to https://github.com/aurelia/cli/issues/508 where a similar error is thrown when you follow the tutorial, because it does not tell you to restart `au run --watch` after adding the bootstrap config to aurelia.json. https://github.com/aurelia/framework/pull/785 should make that more clear, and https://github.com/aurelia/app-contacts/pull/44 updates app-contacts's CLI to 0.29.0

**Comment by Akiyamka** [comment] 2017-05-31 07:27
@JeroenVinke, I checked several times changing stub option, the problem is not in the watcher

**Comment by JeroenVinke** [comment] 2017-05-31 07:41
@Akiyamka could you create a ZIP of the project (without the node_modules folder) and attach it to this issue? That would help me a lot

**Comment by fargs** [comment] 2017-07-09 23:34
I am getting this same error. I am using aurelia cli to do my imports, not webpack. I think the issue is with the noView decorator. When I remove the dependencies parameter ['nprogress/nprogress.css'] the plugin loads properly but the element doesn't work as expected without the css, obviously. I have an existing app but I just included the exact code for loading-indicator from the contacts app and this error came up. Hopefully that helps with the investigation.

**Comment by JeroenVinke** [comment] 2017-07-10 06:39
@fargs could you show relevant code and the aurelia.json? I'd gladly take a closer look

**Comment by StephanBis** [comment] 2017-07-18 11:53
Had the same problem, can confirm that a simple restart (au run --watch) fixed this problem. This should be mentioned in the tutorial.

**Comment by danhendrix** [comment] 2017-07-19 21:43
Agreed with Stephan. I had the same problem, fixed after the restart.

**Comment by JeroenVinke** [comment] 2017-07-20 07:33
@EisenbergEffect it's important that we get https://github.com/aurelia/framework/pull/785 and https://github.com/aurelia/framework/pull/795 into the next docs release

**Comment by EisenbergEffect** [comment] 2017-07-20 14:40
Will do!

**Comment by andy1547** [comment] 2017-07-21 13:31
Re-running au run --watch did not help for me, changing "stub" to false fixed this.
I'm using requirejs.

**Comment by JeroenVinke** [comment] 2017-07-21 13:45
@andy1547 if you'd like me to take a look at what the problem might be, please create a ZIP of your project (without the node_modules folder) and attach it to this issue. If it's a problem with our tutorial we can correct it.

**Comment by andy1547** [comment] 2017-07-21 14:53
[contact-manager-app.zip](https://github.com/aurelia/app-contacts/files/1165873/contact-manager-app.zip)

**Comment by JeroenVinke** [comment] 2017-07-21 15:43
@andy1547 thanks! I've taken a look and it appears to be due to the fact that Less is used as transpiler, and the tutorial doesn't take that option into account.

In aurelia.json there is a "transpiler" object with a source property:

```
  "cssProcessor": {
    "id": "less",
    "displayName": "Less",
    "fileExtension": ".less",
    "source": "src/**/*.less"
  },
```

This source property determines which less/css files are included in the bundle. As you can see the source property only mentions files with the `.less` extension, so the styles.css file you have to add to the project doesn't get bundled. 

There are a couple of options:
1. rename styles.css to `styles.less`
2. change aurelia.json to:
 ```
  "cssProcessor": {
    "id": "less",
    "displayName": "Less",
    "fileExtension": ".less",
    "source": ["src/**/*.less", "src/**/*.css"]
  },
```
so that both less and css files are bundled.

3. change the `stub` property to false so requirejs can load the css file (outside of the bundle) when the page loads.

Option 1 is best in my opinion, because it allows you to use Less. If you do that then you can set `stub` to true again which makes the bundle smaller.

This is something we're going to have to mention in the tutorial.

**Comment by dschaefer-netrix** [comment] 2017-10-09 22:12
Thanks for posting this @Akiyamka ... I ran into this same problem myself (used CLI w/ mostly default settings, but had sass as my css pre-processor) & switching stub to false fixed the issue. Kinda disappointed that this still isn't fixed and/or addressed in some way on http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/contact-manager-tutorial/ given how long it's been.

**Comment by jeraldjamescapao** [comment] 2018-02-07 21:24
I'm near to give up on this framework lol. Every tutorial I follow online has errors!
Currently I am following this: http://aurelia.io/docs/tutorials/creating-a-contact-manager
codes not even working. I always get this error:
plugin.load is not a function

**Comment by JeroenVinke** [comment] 2018-02-08 07:42
@jeraldjamescapao

If you can attach a zip containing all your project files except what’s in node_modules, I can help debug the issue

**Comment by jeraldjamescapao** [comment] 2018-02-08 20:05
Hello JeroenVinke and thanks for replying. actually I resolved it by following this tutorial: http://www.foursails.co/blog/aurelia-cli-bootstrap/
I am a rookie on Javascript Frameworks so pls pardon me.
Cheers,
J

**Comment by Alexander-Taran** [comment] 2018-02-25 03:04
can be closed

**Comment by EisenbergEffect** [comment] 2018-02-25 03:09
@jeraldjamescapao No need to apologize! We're glad you are here and were able to work through the issue. It's a learning experience for all of us every day :)

**Closed as completed** 2018-02-25 03:08 UTC
Labels: bug, question
